version: '2'
services:
  medicalequipmentmanager-app:
    image: medicalequipmentmanager
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://medicalequipmentmanager-mssql:1433;database=MedicalEquipmentManager
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  medicalequipmentmanager-mssql:
    extends:
      file: mssql.yml
      service: medicalequipmentmanager-mssql
